sudo: required

language: generic

services:
  - docker


before_install:
  - docker build -t bvnarayan/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true bvnarayan/docker-react npm run test
